# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#gongler google-ID: 

menu: 
  - name: 菜单
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: 文档
    link: /
  - name: 标签
    link: /tags
  - name: 关于
    link: /about
  - name: 更多链接
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/gongler
      - name: LinkedIn
        icon: linkedin-square
        link: http://
      - name: Twitter
        icon: twitter
        link: https://
    
